### ISSUE TITLE
Use pipenv instead of virtualenv

### ISSUE THREAD

**Issue by ngsankha** [devlup-labs/mug_lo#2]
The current setup mandates the use of a `requirements.txt` and virtualenv. [Pipenv](https://docs.pipenv.org/) is modern and makes it simpler to maintain Python projects, bringing it at par with Ruby, Node.js etc. ecosystems.

**Comment by ajatprabha** [comment]
Thanks for the information @ngsankha I didn't know about this before.
Tried `pipenv` on [`backend`](https://github.com/devlup-labs/mug_lo/commits/backend) branch, it's working great. Will merge soon into `master`.

**Comment by ajatprabha** [comment]
Changes merged into `master`
